using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;

public class StandMoving : MonoBehaviour
{
    private DogStatus dogStatus;
    public Rigidbody standRB;

    //  ï¿½eï¿½sï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½é‚©ï¿½Ì”ï¿½ï¿½ï¿½tï¿½ï¿½ï¿½O
    public bool isJumping = false;

    //  ï¿½ï¿½ï¿½ï¿½ï¿½éƒŒï¿½[ï¿½ï¿½ï¿½ğ”»’è‚·ï¿½é‚½ï¿½ß‚ï¿½intï¿½l
    //  0ï¿½ï¿½ï¿½ï¿½Ôï¿½ï¿½A5ï¿½ï¿½ï¿½ï¿½Ô‰Eï¿½Ìï¿½ï¿½v6ï¿½ï¿½ï¿½[ï¿½ï¿½
    public int laneNamber;

    private bool _isMoving = false;
    private bool _isKeyUp = true;
    public bool canRightMove = true;
    public bool canLeftMove = true;

    [SerializeField]
    private DogMoving _dogMoving;

    private ISPlayerMove _ISPlayerMove;
    [SerializeField]
    private Transform _playerTransform;
    private Vector3 _playerGoToPos;


    [SerializeField]
    private Transform _stickUIMini;
    private Vector2 _stickUIMiniPos;


    private enum MoveType
    {
        None,
        Left,
        Right,
    }

    private Dictionary<MoveType, Vector3> _addVector = new Dictionary<MoveType, Vector3>()
    {
        //  Xï¿½ï¿½floatï¿½ï¿½ï¿½Ú“ï¿½ï¿½ï¿½
        { MoveType.Left, new Vector3(-1.17f, 0, 0) },
        { MoveType.Right, new Vector3(1.17f, 0, 0) },
    };

    [SerializeField]
    public int _connectGamepadNum;
    public Gamepad _connectGamepad;

    [SerializeField]
    private SushiJump sushiJump;


    /// <summary>
    /// Scene ï¿½Jï¿½nï¿½ï¿½ï¿½ï¿½
    /// </summary>
    void Start()
    {
        standRB = GetComponent<Rigidbody>();
        dogStatus = GetComponent<DogStatus>();

        _ISPlayerMove = new ISPlayerMove();
        _ISPlayerMove.Enable();

        //  ï¿½Rï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½[ï¿½Ú‘ï¿½ï¿½Uï¿½è•ªï¿½ï¿½
        _connectGamepad = Gamepad.all[_connectGamepadNum];

        //  ï¿½Tï¿½[ï¿½ï¿½ï¿½ï¿½
        if(_connectGamepadNum == 0)
        {
            laneNamber = 1;
        }
        //  ï¿½}ï¿½Oï¿½ï¿½
        else if(_connectGamepadNum == 1)
        {
            laneNamber = 4;
        }

        /*
        //  ï¿½fï¿½oï¿½bï¿½Nï¿½pï¿½ï¿½ï¿½ï¿½ï¿½İ’ï¿½
        //  ï¿½ï¿½ï¿½ï¿½ï¿½Åƒoï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ÄAISPlayerMoveï¿½ï¿½ï¿½Ì‚ï¿½ï¿½Ì‚ï¿½nullï¿½É‚È‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½B
        tunaJump = ISPlayerMove.DebugTuna.Jump;
        salmonJump = ISPlayerMove.DebugSalmon.Jump;
        */

        _stickUIMiniPos = _stickUIMini.position;
    }

    // Update is called once per frame
    void Update()
    {
        PlayerMove();
        PlayerJump();

        _dogMoving.isJumping = isJumping;
        /*
        //  ï¿½uï¿½Jï¿½[ï¿½uï¿½ï¿½ï¿½vï¿½È‚ï¿½A
        if (_isCurving)
            CurveMoveLimit(dogStatus._maxMoveLimit);
        */
    }

    public void PlayerJump()
    {
        if(isJumping == false)
        {
            //  ï¿½Rï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½[ï¿½Ú‘ï¿½ï¿½ï¿½ï¿½ÌƒWï¿½ï¿½ï¿½ï¿½ï¿½v
            if (_connectGamepad != null)
            {
                //  ï¿½Lï¿½[ï¿½{ï¿½[ï¿½hï¿½Ì‰ï¿½ï¿½É‚ï¿½ï¿½ï¿½{ï¿½^ï¿½ï¿½(XBOXï¿½È‚ï¿½Aï¿½{ï¿½^ï¿½ï¿½)ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì”ï¿½ï¿½ï¿½
                bool inputPress = _connectGamepad.buttonSouth.wasPressedThisFrame;
                if(inputPress)
                {
                    //dogMoving.isJumping = true;
                    
                    if(_connectGamepadNum == 0)
                        sushiJump.isSalmonJump = true;
                    if(_connectGamepadNum == 1)
                        sushiJump.isMaguroJump = true;
                }
                else
                {
                    if (_connectGamepadNum == 0)
                        sushiJump.isSalmonJump = false;
                    if (_connectGamepadNum == 1)
                        sushiJump.isMaguroJump = false;
                }
            }
        }
    }

    /// <summary>
    /// ï¿½ï¿½ï¿½iï¿½ï¿½ï¿½Ìï¿½ï¿½Eï¿½ÌˆÚ“ï¿½ï¿½ï¿½ï¿½ï¿½
    /// </summary>
    private void PlayerMove()
    {
        
        //  ï¿½uï¿½Ú“ï¿½ï¿½ï¿½ï¿½vï¿½Å‚È‚ï¿½ï¿½Aï¿½uï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½vï¿½Å‚È‚ï¿½ï¿½ï¿½ï¿½
        if (!_isMoving && !isJumping)
        {
            //  ï¿½uï¿½ï¿½ï¿½Í’ï¿½ï¿½vï¿½Å‚È‚ï¿½ï¿½ï¿½ï¿½
            if (_isKeyUp)
            {
                float inputX = 0;
                if (_connectGamepad != null)
                {
                    //  InputSystem ï¿½ï¿½ value ï¿½ï¿½Ç‚İï¿½ï¿½ï¿½
                    inputX = _connectGamepad.leftStick.x.ReadValue();
                }
                //  ï¿½ï¿½ï¿½Ì“ï¿½ï¿½Í‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                if (inputX != 0)
                {
                    //  ï¿½uï¿½ï¿½ï¿½Í’ï¿½ï¿½vï¿½ï¿½
                    _isKeyUp = false;
                    //  ï¿½ï¿½ï¿½İ‚ï¿½ position ï¿½ï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½ê‚¼ï¿½ï¿½É‰ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Z
                    _playerGoToPos = _playerTransform.position;
                    

                    //  ï¿½Eï¿½Ú“ï¿½
                    if (inputX > 0)
                    {
                        //  ï¿½Xï¿½eï¿½Bï¿½bï¿½Nï¿½ï¿½ï¿½Í‚ï¿½UIï¿½ï¿½ï¿½ï¿½
                        _stickUIMiniPos = new Vector2(20f, 0);
                        _stickUIMini.transform.localPosition = _stickUIMiniPos;

                        if (canRightMove)
                        {
                            _playerGoToPos += _addVector[MoveType.Right];
                            laneNamber++;
                            laneNamber = Mathf.Min(laneNamber, 5);
                        }}
                    //  ï¿½ï¿½ï¿½Ú“ï¿½
                    else if (inputX < 0)
                    {
                        //  ï¿½Xï¿½eï¿½Bï¿½bï¿½Nï¿½ï¿½ï¿½Í‚ï¿½UIï¿½ï¿½ï¿½ï¿½
                        _stickUIMiniPos = new Vector2(-20f, 0);
                        _stickUIMini.transform.localPosition = _stickUIMiniPos;

                        if (canLeftMove)
                        {
                            _playerGoToPos += _addVector[MoveType.Left];
                            laneNamber--;
                            laneNamber = Mathf.Max(0, laneNamber);
                        }
                    }
                    //if(canRightMove && canLeftMove)
                    StartCoroutine(MoveCor());
                }
            }
            else
            {
                //  InputSystem ï¿½ï¿½ value ï¿½ï¿½Ç‚İï¿½ï¿½ï¿½
                //var inputVal = dogController.Player.Move.ReadValue<Vector2>();
                float inputX = _connectGamepad.leftStick.x.ReadValue();
                if (inputX == 0)
                {
                    _isKeyUp = true;
                    canLeftMove = true;
                    canRightMove = true;

                    _stickUIMini.transform.localPosition = Vector3.zero;
                }
            }
        }
    }

    /*
    /// <summary>
    /// ï¿½Jï¿½[ï¿½uï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½(ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½)
    /// </summary>
    /// <param name="MaxMoveLimit"></param>
    private void CurveMoveLimit(float MaxMoveLimit)
    {
        //  ï¿½Ú“ï¿½ï¿½ï¿½ï¿½xï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Â‚ï¿½ï¿½ÄŠï¿½ï¿½ç‚©ï¿½É“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½...ï¿½Í‚ï¿½ï¿½H
        float _currentMoveSpeed = standRB.velocity.z;
        if (_currentMoveSpeed > MaxMoveLimit)
        {
            _currentMoveSpeed /= MaxMoveLimit;
            standRB.velocity = new Vector3(
                standRB.velocity.x,
                standRB.velocity.y,
                _currentMoveSpeed);
        }
    }*/

    /// <summary>
    /// ï¿½ï¿½ï¿½Eï¿½ÌŠï¿½ï¿½ç‚©ï¿½ÈˆÚ“ï¿½ï¿½Rï¿½ï¿½ï¿½[ï¿½`ï¿½ï¿½
    /// </summary>
    /// <returns></returns>
    private IEnumerator MoveCor()
    {
        //  ï¿½uï¿½Ú“ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½
        _isMoving = true;
        //  _moveTimer ï¿½bï¿½oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½Jï¿½ï¿½Ô‚ï¿½ï¿½ï¿½ï¿½ï¿½
        //  1fï¿½Æï¿½ï¿½ï¿½ï¿½Ä‚Í‚ï¿½ï¿½é‚ªï¿½A1ï¿½bï¿½ÅIï¿½ï¿½ï¿½í‚¯ï¿½Å‚Í‚È‚ï¿½ï¿½B
        float actionTimer = 0f;
        while (actionTimer < 1f)
        {
            actionTimer += Time.deltaTime / dogStatus._moveTimer;
            actionTimer = Mathf.Min(actionTimer, 1f);
            //  ï¿½ï¿½ï¿½^ï¿½ï¿½Ô‚ï¿½ï¿½gï¿½ï¿½ï¿½Ä“ï¿½ï¿½ï¿½ï¿½ÌˆÚ“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Rï¿½ï¿½
            var movingPos = _playerTransform.position;
            movingPos.x = Mathf.Lerp(_playerTransform.position.x, _playerGoToPos.x, actionTimer);
            _playerTransform.position = movingPos;
            yield return null;
        }
        //  ï¿½uï¿½Ú“ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ false ï¿½ï¿½
        _isMoving = false;
    }
}
